# Generated by Django 5.0.6 on 2024-07-12 05:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('pincode', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('role', models.CharField(default='customer', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_old_price', models.FloatField(max_length=10)),
                ('product_discount', models.FloatField(max_length=10)),
                ('product_size', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_availability', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_img', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetail', to='E_Commerse.productdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_size', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_img', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerorder', to='E_Commerse.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetailsorder', to='E_Commerse.productdetail')),
                ('product_img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimageorder', to='E_Commerse.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_img', models.CharField(max_length=200)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_size', models.CharField(max_length=20)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_total_price', models.FloatField(max_length=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='E_Commerse.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='E_Commerse.productdetail')),
                ('product_img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimage', to='E_Commerse.productimage')),
            ],
        ),
    ]
