# Generated by Django 5.0.6 on 2024-07-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forgot_password_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
